/**
 * Jogos da Copa do Mundo FIFA 2026 (horarios de Brasilia)
 * ARQUIVO GERADO AUTOMATICAMENTE -- nao edite a mao.
 * Origem: fontes/copa2026_jogos_primeira_fase.txt, copa2026_Jogos_Segunda_fase.txt, copa2026_jogos_oitavas.txt, copa2026_jogos_quartas.txt, copa2026_jogos_semifinal.txt, copa2026_jogo_terceiro_lugar.txt, copa2026_jogo_final.txt
 * Gerador: tools/gerar-dados.mjs
 */
window.COPA26_JOGOS = [
  {
    "numero": 1,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G01",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "MEX",
    "visitante": "RSA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-11",
    "hora": "16:00",
    "diaTabela": "2026-06-11",
    "estadio": "cidade-do-mexico"
  },
  {
    "numero": 2,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G02",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "KOR",
    "visitante": "CZE",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-11",
    "hora": "23:00",
    "diaTabela": "2026-06-11",
    "estadio": "guadalajara"
  },
  {
    "numero": 3,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G03",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "CAN",
    "visitante": "BIH",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-12",
    "hora": "16:00",
    "diaTabela": "2026-06-12",
    "estadio": "toronto"
  },
  {
    "numero": 4,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G04",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "USA",
    "visitante": "PAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-12",
    "hora": "22:00",
    "diaTabela": "2026-06-12",
    "estadio": "los-angeles"
  },
  {
    "numero": 5,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G05",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "QAT",
    "visitante": "SUI",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-13",
    "hora": "16:00",
    "diaTabela": "2026-06-13",
    "estadio": "san-francisco"
  },
  {
    "numero": 6,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G06",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "BRA",
    "visitante": "MAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-13",
    "hora": "19:00",
    "diaTabela": "2026-06-13",
    "estadio": "nova-york"
  },
  {
    "numero": 7,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G07",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "HAI",
    "visitante": "SCO",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-13",
    "hora": "22:00",
    "diaTabela": "2026-06-13",
    "estadio": "boston"
  },
  {
    "numero": 8,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G08",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "AUS",
    "visitante": "TUR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-14",
    "hora": "01:00",
    "diaTabela": "2026-06-13",
    "estadio": "vancouver"
  },
  {
    "numero": 9,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G09",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "GER",
    "visitante": "CUW",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-14",
    "hora": "14:00",
    "diaTabela": "2026-06-14",
    "estadio": "houston"
  },
  {
    "numero": 10,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G10",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "NED",
    "visitante": "JPN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-14",
    "hora": "17:00",
    "diaTabela": "2026-06-14",
    "estadio": "dallas"
  },
  {
    "numero": 11,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G11",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "CIV",
    "visitante": "ECU",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-14",
    "hora": "20:00",
    "diaTabela": "2026-06-14",
    "estadio": "filadelfia"
  },
  {
    "numero": 12,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G12",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "SWE",
    "visitante": "TUN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-14",
    "hora": "23:00",
    "diaTabela": "2026-06-14",
    "estadio": "monterrey"
  },
  {
    "numero": 13,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G13",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "ESP",
    "visitante": "CPV",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-15",
    "hora": "13:00",
    "diaTabela": "2026-06-15",
    "estadio": "atlanta"
  },
  {
    "numero": 14,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G14",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "BEL",
    "visitante": "EGY",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-15",
    "hora": "16:00",
    "diaTabela": "2026-06-15",
    "estadio": "seattle"
  },
  {
    "numero": 15,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G15",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "KSA",
    "visitante": "URU",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-15",
    "hora": "19:00",
    "diaTabela": "2026-06-15",
    "estadio": "miami"
  },
  {
    "numero": 16,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G16",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "IRN",
    "visitante": "NZL",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-15",
    "hora": "22:00",
    "diaTabela": "2026-06-15",
    "estadio": "los-angeles"
  },
  {
    "numero": 17,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G17",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "FRA",
    "visitante": "SEN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-16",
    "hora": "16:00",
    "diaTabela": "2026-06-16",
    "estadio": "nova-york"
  },
  {
    "numero": 18,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G18",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "IRQ",
    "visitante": "NOR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-16",
    "hora": "19:00",
    "diaTabela": "2026-06-16",
    "estadio": "boston"
  },
  {
    "numero": 19,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G19",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "ARG",
    "visitante": "ALG",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-16",
    "hora": "22:00",
    "diaTabela": "2026-06-16",
    "estadio": "kansas-city"
  },
  {
    "numero": 20,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G20",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "AUT",
    "visitante": "JOR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-17",
    "hora": "01:00",
    "diaTabela": "2026-06-16",
    "estadio": "san-francisco"
  },
  {
    "numero": 21,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G21",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "POR",
    "visitante": "COD",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-17",
    "hora": "14:00",
    "diaTabela": "2026-06-17",
    "estadio": "houston"
  },
  {
    "numero": 22,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G22",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "ENG",
    "visitante": "CRO",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-17",
    "hora": "17:00",
    "diaTabela": "2026-06-17",
    "estadio": "dallas"
  },
  {
    "numero": 23,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G23",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "GHA",
    "visitante": "PAN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-17",
    "hora": "20:00",
    "diaTabela": "2026-06-17",
    "estadio": "toronto"
  },
  {
    "numero": 24,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G24",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "UZB",
    "visitante": "COL",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-17",
    "hora": "23:00",
    "diaTabela": "2026-06-17",
    "estadio": "cidade-do-mexico"
  },
  {
    "numero": 25,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G25",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "CZE",
    "visitante": "RSA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-18",
    "hora": "13:00",
    "diaTabela": "2026-06-18",
    "estadio": "atlanta"
  },
  {
    "numero": 26,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G26",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "SUI",
    "visitante": "BIH",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-18",
    "hora": "16:00",
    "diaTabela": "2026-06-18",
    "estadio": "los-angeles"
  },
  {
    "numero": 27,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G27",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "CAN",
    "visitante": "QAT",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-18",
    "hora": "19:00",
    "diaTabela": "2026-06-18",
    "estadio": "vancouver"
  },
  {
    "numero": 28,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G28",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "MEX",
    "visitante": "KOR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-18",
    "hora": "22:00",
    "diaTabela": "2026-06-18",
    "estadio": "guadalajara"
  },
  {
    "numero": 29,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G29",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "USA",
    "visitante": "AUS",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-19",
    "hora": "16:00",
    "diaTabela": "2026-06-19",
    "estadio": "seattle"
  },
  {
    "numero": 30,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G30",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "SCO",
    "visitante": "MAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-19",
    "hora": "19:00",
    "diaTabela": "2026-06-19",
    "estadio": "boston"
  },
  {
    "numero": 31,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G31",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "BRA",
    "visitante": "HAI",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-19",
    "hora": "21:30",
    "diaTabela": "2026-06-19",
    "estadio": "filadelfia"
  },
  {
    "numero": 32,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G32",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "TUR",
    "visitante": "PAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-20",
    "hora": "00:00",
    "diaTabela": "2026-06-19",
    "estadio": "san-francisco"
  },
  {
    "numero": 33,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G33",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "NED",
    "visitante": "SWE",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-20",
    "hora": "14:00",
    "diaTabela": "2026-06-20",
    "estadio": "houston"
  },
  {
    "numero": 34,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G34",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "GER",
    "visitante": "CIV",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-20",
    "hora": "17:00",
    "diaTabela": "2026-06-20",
    "estadio": "toronto"
  },
  {
    "numero": 35,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G35",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "ECU",
    "visitante": "CUW",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-20",
    "hora": "21:00",
    "diaTabela": "2026-06-20",
    "estadio": "kansas-city"
  },
  {
    "numero": 36,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G36",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "TUN",
    "visitante": "JPN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-21",
    "hora": "01:00",
    "diaTabela": "2026-06-20",
    "estadio": "monterrey"
  },
  {
    "numero": 37,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G37",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "ESP",
    "visitante": "KSA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-21",
    "hora": "13:00",
    "diaTabela": "2026-06-21",
    "estadio": "atlanta"
  },
  {
    "numero": 38,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G38",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "BEL",
    "visitante": "IRN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-21",
    "hora": "16:00",
    "diaTabela": "2026-06-21",
    "estadio": "los-angeles"
  },
  {
    "numero": 39,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G39",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "URU",
    "visitante": "CPV",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-21",
    "hora": "19:00",
    "diaTabela": "2026-06-21",
    "estadio": "miami"
  },
  {
    "numero": 40,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G40",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "NZL",
    "visitante": "EGY",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-21",
    "hora": "22:00",
    "diaTabela": "2026-06-21",
    "estadio": "vancouver"
  },
  {
    "numero": 41,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G41",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "ARG",
    "visitante": "AUT",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-22",
    "hora": "14:00",
    "diaTabela": "2026-06-22",
    "estadio": "dallas"
  },
  {
    "numero": 42,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G42",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "FRA",
    "visitante": "IRQ",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-22",
    "hora": "18:00",
    "diaTabela": "2026-06-22",
    "estadio": "filadelfia"
  },
  {
    "numero": 43,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G43",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "NOR",
    "visitante": "SEN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-22",
    "hora": "21:00",
    "diaTabela": "2026-06-22",
    "estadio": "nova-york"
  },
  {
    "numero": 44,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G44",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "JOR",
    "visitante": "ALG",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-23",
    "hora": "00:00",
    "diaTabela": "2026-06-22",
    "estadio": "san-francisco"
  },
  {
    "numero": 45,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G45",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "POR",
    "visitante": "UZB",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-23",
    "hora": "14:00",
    "diaTabela": "2026-06-23",
    "estadio": "houston"
  },
  {
    "numero": 46,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G46",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "ENG",
    "visitante": "GHA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-23",
    "hora": "17:00",
    "diaTabela": "2026-06-23",
    "estadio": "boston"
  },
  {
    "numero": 47,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G47",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "PAN",
    "visitante": "CRO",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-23",
    "hora": "20:00",
    "diaTabela": "2026-06-23",
    "estadio": "toronto"
  },
  {
    "numero": 48,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G48",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "COL",
    "visitante": "COD",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-23",
    "hora": "23:00",
    "diaTabela": "2026-06-23",
    "estadio": "guadalajara"
  },
  {
    "numero": 49,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G49",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "SUI",
    "visitante": "CAN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "16:00",
    "diaTabela": "2026-06-24",
    "estadio": "vancouver"
  },
  {
    "numero": 50,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G50",
    "fase": "grupos",
    "grupo": "B",
    "mandante": "BIH",
    "visitante": "QAT",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "16:00",
    "diaTabela": "2026-06-24",
    "estadio": "seattle"
  },
  {
    "numero": 51,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G51",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "SCO",
    "visitante": "BRA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "19:00",
    "diaTabela": "2026-06-24",
    "estadio": "miami"
  },
  {
    "numero": 52,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G52",
    "fase": "grupos",
    "grupo": "C",
    "mandante": "MAR",
    "visitante": "HAI",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "19:00",
    "diaTabela": "2026-06-24",
    "estadio": "atlanta"
  },
  {
    "numero": 53,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G53",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "CZE",
    "visitante": "MEX",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "22:00",
    "diaTabela": "2026-06-24",
    "estadio": "cidade-do-mexico"
  },
  {
    "numero": 54,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G54",
    "fase": "grupos",
    "grupo": "A",
    "mandante": "RSA",
    "visitante": "KOR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-24",
    "hora": "22:00",
    "diaTabela": "2026-06-24",
    "estadio": "monterrey"
  },
  {
    "numero": 55,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G55",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "ECU",
    "visitante": "GER",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "17:00",
    "diaTabela": "2026-06-25",
    "estadio": "nova-york"
  },
  {
    "numero": 56,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G56",
    "fase": "grupos",
    "grupo": "E",
    "mandante": "CUW",
    "visitante": "CIV",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "17:00",
    "diaTabela": "2026-06-25",
    "estadio": "filadelfia"
  },
  {
    "numero": 57,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G57",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "JPN",
    "visitante": "SWE",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "20:00",
    "diaTabela": "2026-06-25",
    "estadio": "dallas"
  },
  {
    "numero": 58,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G58",
    "fase": "grupos",
    "grupo": "F",
    "mandante": "TUN",
    "visitante": "NED",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "20:00",
    "diaTabela": "2026-06-25",
    "estadio": "kansas-city"
  },
  {
    "numero": 59,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G59",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "TUR",
    "visitante": "USA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "23:00",
    "diaTabela": "2026-06-25",
    "estadio": "los-angeles"
  },
  {
    "numero": 60,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G60",
    "fase": "grupos",
    "grupo": "D",
    "mandante": "PAR",
    "visitante": "AUS",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-25",
    "hora": "23:00",
    "diaTabela": "2026-06-25",
    "estadio": "san-francisco"
  },
  {
    "numero": 61,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G61",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "NOR",
    "visitante": "FRA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-26",
    "hora": "16:00",
    "diaTabela": "2026-06-26",
    "estadio": "boston"
  },
  {
    "numero": 62,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G62",
    "fase": "grupos",
    "grupo": "I",
    "mandante": "SEN",
    "visitante": "IRQ",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-26",
    "hora": "16:00",
    "diaTabela": "2026-06-26",
    "estadio": "toronto"
  },
  {
    "numero": 63,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G63",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "CPV",
    "visitante": "KSA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-26",
    "hora": "21:00",
    "diaTabela": "2026-06-26",
    "estadio": "houston"
  },
  {
    "numero": 64,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G64",
    "fase": "grupos",
    "grupo": "H",
    "mandante": "URU",
    "visitante": "ESP",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-26",
    "hora": "21:00",
    "diaTabela": "2026-06-26",
    "estadio": "guadalajara"
  },
  {
    "numero": 65,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G65",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "EGY",
    "visitante": "IRN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "00:00",
    "diaTabela": "2026-06-26",
    "estadio": "seattle"
  },
  {
    "numero": 66,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G66",
    "fase": "grupos",
    "grupo": "G",
    "mandante": "NZL",
    "visitante": "BEL",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "00:00",
    "diaTabela": "2026-06-26",
    "estadio": "vancouver"
  },
  {
    "numero": 67,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G67",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "PAN",
    "visitante": "ENG",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "18:00",
    "diaTabela": "2026-06-27",
    "estadio": "nova-york"
  },
  {
    "numero": 68,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G68",
    "fase": "grupos",
    "grupo": "L",
    "mandante": "CRO",
    "visitante": "GHA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "18:00",
    "diaTabela": "2026-06-27",
    "estadio": "filadelfia"
  },
  {
    "numero": 69,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G69",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "COL",
    "visitante": "POR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "20:30",
    "diaTabela": "2026-06-27",
    "estadio": "miami"
  },
  {
    "numero": 70,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G70",
    "fase": "grupos",
    "grupo": "K",
    "mandante": "COD",
    "visitante": "UZB",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "20:30",
    "diaTabela": "2026-06-27",
    "estadio": "atlanta"
  },
  {
    "numero": 71,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G71",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "ALG",
    "visitante": "AUT",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "23:00",
    "diaTabela": "2026-06-27",
    "estadio": "kansas-city"
  },
  {
    "numero": 72,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "G72",
    "fase": "grupos",
    "grupo": "J",
    "mandante": "JOR",
    "visitante": "ARG",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-27",
    "hora": "23:00",
    "diaTabela": "2026-06-27",
    "estadio": "dallas"
  },
  {
    "numero": 73,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF03",
    "fase": "segunda-fase",
    "ordem": 3,
    "grupo": null,
    "mandante": "RSA",
    "visitante": "CAN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-28",
    "hora": "16:00",
    "diaTabela": "2026-06-28",
    "estadio": "los-angeles"
  },
  {
    "numero": 74,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF09",
    "fase": "segunda-fase",
    "ordem": 9,
    "grupo": null,
    "mandante": "BRA",
    "visitante": "JPN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-29",
    "hora": "14:00",
    "diaTabela": "2026-06-29",
    "estadio": "houston"
  },
  {
    "numero": 75,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF01",
    "fase": "segunda-fase",
    "ordem": 1,
    "grupo": null,
    "mandante": "GER",
    "visitante": "PAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-29",
    "hora": "17:30",
    "diaTabela": "2026-06-29",
    "estadio": "boston"
  },
  {
    "numero": 76,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF04",
    "fase": "segunda-fase",
    "ordem": 4,
    "grupo": null,
    "mandante": "NED",
    "visitante": "MAR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-29",
    "hora": "22:00",
    "diaTabela": "2026-06-29",
    "estadio": "monterrey"
  },
  {
    "numero": 77,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF10",
    "fase": "segunda-fase",
    "ordem": 10,
    "grupo": null,
    "mandante": "CIV",
    "visitante": "NOR",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-30",
    "hora": "14:00",
    "diaTabela": "2026-06-30",
    "estadio": "dallas"
  },
  {
    "numero": 78,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF02",
    "fase": "segunda-fase",
    "ordem": 2,
    "grupo": null,
    "mandante": "FRA",
    "visitante": "SWE",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-30",
    "hora": "18:00",
    "diaTabela": "2026-06-30",
    "estadio": "nova-york"
  },
  {
    "numero": 79,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF11",
    "fase": "segunda-fase",
    "ordem": 11,
    "grupo": null,
    "mandante": "MEX",
    "visitante": "ECU",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-06-30",
    "hora": "22:00",
    "diaTabela": "2026-06-30",
    "estadio": "cidade-do-mexico"
  },
  {
    "numero": 80,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF12",
    "fase": "segunda-fase",
    "ordem": 12,
    "grupo": null,
    "mandante": "ENG",
    "visitante": "COD",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-01",
    "hora": "13:00",
    "diaTabela": "2026-07-01",
    "estadio": "atlanta"
  },
  {
    "numero": 81,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF08",
    "fase": "segunda-fase",
    "ordem": 8,
    "grupo": null,
    "mandante": "BEL",
    "visitante": "SEN",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-01",
    "hora": "17:00",
    "diaTabela": "2026-07-01",
    "estadio": "seattle"
  },
  {
    "numero": 82,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF07",
    "fase": "segunda-fase",
    "ordem": 7,
    "grupo": null,
    "mandante": "USA",
    "visitante": "BIH",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-01",
    "hora": "21:00",
    "diaTabela": "2026-07-01",
    "estadio": "san-francisco"
  },
  {
    "numero": 83,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF06",
    "fase": "segunda-fase",
    "ordem": 6,
    "grupo": null,
    "mandante": "ESP",
    "visitante": "AUT",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-02",
    "hora": "16:00",
    "diaTabela": "2026-07-02",
    "estadio": "los-angeles"
  },
  {
    "numero": 84,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF05",
    "fase": "segunda-fase",
    "ordem": 5,
    "grupo": null,
    "mandante": "POR",
    "visitante": "CRO",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-02",
    "hora": "20:00",
    "diaTabela": "2026-07-02",
    "estadio": "toronto"
  },
  {
    "numero": 85,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF15",
    "fase": "segunda-fase",
    "ordem": 15,
    "grupo": null,
    "mandante": "SUI",
    "visitante": "ALG",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-03",
    "hora": "00:00",
    "diaTabela": "2026-07-03",
    "estadio": "vancouver"
  },
  {
    "numero": 86,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF14",
    "fase": "segunda-fase",
    "ordem": 14,
    "grupo": null,
    "mandante": "AUS",
    "visitante": "EGY",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-03",
    "hora": "15:00",
    "diaTabela": "2026-07-03",
    "estadio": "dallas"
  },
  {
    "numero": 87,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF13",
    "fase": "segunda-fase",
    "ordem": 13,
    "grupo": null,
    "mandante": "ARG",
    "visitante": "CPV",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-03",
    "hora": "19:00",
    "diaTabela": "2026-07-03",
    "estadio": "miami"
  },
  {
    "numero": 88,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SF16",
    "fase": "segunda-fase",
    "ordem": 16,
    "grupo": null,
    "mandante": "COL",
    "visitante": "GHA",
    "mandanteRef": null,
    "visitanteRef": null,
    "data": "2026-07-03",
    "hora": "22:30",
    "diaTabela": "2026-07-03",
    "estadio": "kansas-city"
  },
  {
    "numero": 89,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI02",
    "fase": "oitavas",
    "ordem": 2,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF03"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF04"
    },
    "data": "2026-07-04",
    "hora": "14:00",
    "diaTabela": "2026-07-04",
    "estadio": "houston",
    "rotuloFonte": "Oitavas 2"
  },
  {
    "numero": 90,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI01",
    "fase": "oitavas",
    "ordem": 1,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF01"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF02"
    },
    "data": "2026-07-04",
    "hora": "18:00",
    "diaTabela": "2026-07-04",
    "estadio": "filadelfia",
    "rotuloFonte": "Oitavas 1"
  },
  {
    "numero": 91,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI05",
    "fase": "oitavas",
    "ordem": 5,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF09"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF10"
    },
    "data": "2026-07-05",
    "hora": "17:00",
    "diaTabela": "2026-07-05",
    "estadio": "nova-york",
    "rotuloFonte": "Oitavas 5"
  },
  {
    "numero": 92,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI06",
    "fase": "oitavas",
    "ordem": 6,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF11"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF12"
    },
    "data": "2026-07-05",
    "hora": "21:00",
    "diaTabela": "2026-07-05",
    "estadio": "cidade-do-mexico",
    "rotuloFonte": "Oitavas 6"
  },
  {
    "numero": 93,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI03",
    "fase": "oitavas",
    "ordem": 3,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF05"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF06"
    },
    "data": "2026-07-06",
    "hora": "16:00",
    "diaTabela": "2026-07-06",
    "estadio": "dallas",
    "rotuloFonte": "Oitavas 3"
  },
  {
    "numero": 94,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI04",
    "fase": "oitavas",
    "ordem": 4,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF07"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF08"
    },
    "data": "2026-07-06",
    "hora": "21:00",
    "diaTabela": "2026-07-06",
    "estadio": "seattle",
    "rotuloFonte": "Oitavas 4"
  },
  {
    "numero": 95,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI07",
    "fase": "oitavas",
    "ordem": 7,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF13"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF14"
    },
    "data": "2026-07-07",
    "hora": "13:00",
    "diaTabela": "2026-07-07",
    "estadio": "atlanta",
    "rotuloFonte": "Oitavas 7"
  },
  {
    "numero": 96,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "OI08",
    "fase": "oitavas",
    "ordem": 8,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SF15"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SF16"
    },
    "data": "2026-07-07",
    "hora": "17:00",
    "diaTabela": "2026-07-07",
    "estadio": "vancouver",
    "rotuloFonte": "Oitavas 8"
  },
  {
    "numero": 97,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "QF01",
    "fase": "quartas",
    "ordem": 1,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "OI01"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "OI02"
    },
    "data": "2026-07-09",
    "hora": "17:00",
    "diaTabela": "2026-07-09",
    "estadio": "boston",
    "rotuloFonte": "Quartas 1"
  },
  {
    "numero": 98,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "QF02",
    "fase": "quartas",
    "ordem": 2,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "OI03"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "OI04"
    },
    "data": "2026-07-10",
    "hora": "16:00",
    "diaTabela": "2026-07-10",
    "estadio": "los-angeles",
    "rotuloFonte": "Quartas 2"
  },
  {
    "numero": 99,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "QF03",
    "fase": "quartas",
    "ordem": 3,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "OI05"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "OI06"
    },
    "data": "2026-07-11",
    "hora": "18:00",
    "diaTabela": "2026-07-11",
    "estadio": "miami",
    "rotuloFonte": "Quartas 3"
  },
  {
    "numero": 100,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "QF04",
    "fase": "quartas",
    "ordem": 4,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "OI07"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "OI08"
    },
    "data": "2026-07-11",
    "hora": "22:00",
    "diaTabela": "2026-07-11",
    "estadio": "kansas-city",
    "rotuloFonte": "Quartas 4"
  },
  {
    "numero": 101,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SM01",
    "fase": "semifinal",
    "ordem": 1,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "QF01"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "QF02"
    },
    "data": "2026-07-14",
    "hora": "16:00",
    "diaTabela": "2026-07-14",
    "estadio": "dallas",
    "rotuloFonte": "Semifinal 1"
  },
  {
    "numero": 102,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "SM02",
    "fase": "semifinal",
    "ordem": 2,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "QF03"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "QF04"
    },
    "data": "2026-07-15",
    "hora": "16:00",
    "diaTabela": "2026-07-15",
    "estadio": "atlanta",
    "rotuloFonte": "Semifinal 2"
  },
  {
    "numero": 103,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "TL01",
    "fase": "terceiro-lugar",
    "ordem": 1,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "perdedor",
      "jogo": "SM01"
    },
    "visitanteRef": {
      "tipo": "perdedor",
      "jogo": "SM02"
    },
    "data": "2026-07-18",
    "hora": "18:00",
    "diaTabela": "2026-07-18",
    "estadio": "miami",
    "rotuloFonte": "Terceiro lugar 1"
  },
  {
    "numero": 104,
    "placarMandante": null,
    "placarVisitante": null,
    "status": "Agendado",
    "id": "FI01",
    "fase": "final",
    "ordem": 1,
    "grupo": null,
    "mandante": null,
    "visitante": null,
    "mandanteRef": {
      "tipo": "vencedor",
      "jogo": "SM01"
    },
    "visitanteRef": {
      "tipo": "vencedor",
      "jogo": "SM02"
    },
    "data": "2026-07-19",
    "hora": "16:00",
    "diaTabela": "2026-07-19",
    "estadio": "nova-york",
    "rotuloFonte": "Final 1"
  }
];
