/**
 * Selecoes participantes da Copa do Mundo FIFA 2026
 * ARQUIVO GERADO AUTOMATICAMENTE -- nao edite a mao.
 * Origem: fontes/copa2026_grupos.txt, copa2026_cabecas-chave.txt, copa2026_pais_tecnicos.txt, copa2026_ranking_fifa.txt
 * Gerador: tools/gerar-dados.mjs
 */
window.COPA26_SELECOES = [
  {
    "cod": "MEX",
    "nome": "México",
    "grupo": "A",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "CONCACAF",
    "tecnico": "Javier Aguirre",
    "rankingPosicao": 15,
    "rankingPontos": 1685.68,
    "rankingOrdem": 15,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/MEX"
  },
  {
    "cod": "RSA",
    "nome": "África do Sul",
    "grupo": "A",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Hugo Broos",
    "rankingPosicao": 74,
    "rankingPontos": 1332.99,
    "rankingOrdem": 74,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/RSA"
  },
  {
    "cod": "KOR",
    "nome": "Coreia do Sul",
    "grupo": "A",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Hong Myung-bo",
    "rankingPosicao": 25,
    "rankingPontos": 1590.69,
    "rankingOrdem": 25,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/KOR"
  },
  {
    "cod": "CZE",
    "nome": "Tchéquia",
    "grupo": "A",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Miroslav Koubek",
    "rankingPosicao": 39,
    "rankingPontos": 1510.15,
    "rankingOrdem": 39,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CZE"
  },
  {
    "cod": "CAN",
    "nome": "Canadá",
    "grupo": "B",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "CONCACAF",
    "tecnico": "Jesse Marsch",
    "rankingPosicao": 24,
    "rankingPontos": 1599.2,
    "rankingOrdem": 24,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CAN"
  },
  {
    "cod": "BIH",
    "nome": "Bósnia e Herzegovina",
    "grupo": "B",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Sergej Barbarez",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/BIH"
  },
  {
    "cod": "QAT",
    "nome": "Catar",
    "grupo": "B",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Julen Lopetegui",
    "rankingPosicao": 55,
    "rankingPontos": 1419.02,
    "rankingOrdem": 55,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/QAT"
  },
  {
    "cod": "SUI",
    "nome": "Suíça",
    "grupo": "B",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Murat Yakin",
    "rankingPosicao": 19,
    "rankingPontos": 1652.43,
    "rankingOrdem": 19,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/SUI"
  },
  {
    "cod": "BRA",
    "nome": "Brasil",
    "grupo": "C",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "CONMEBOL",
    "tecnico": "Carlo Ancelotti",
    "rankingPosicao": 6,
    "rankingPontos": 1765.86,
    "rankingOrdem": 6,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/BRA"
  },
  {
    "cod": "MAR",
    "nome": "Marrocos",
    "grupo": "C",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Mohamed Ouahbi",
    "rankingPosicao": 7,
    "rankingPontos": 1755.1,
    "rankingOrdem": 7,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/MAR"
  },
  {
    "cod": "HAI",
    "nome": "Haiti",
    "grupo": "C",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "CONCACAF",
    "tecnico": "Sébastien Migné",
    "rankingPosicao": 63,
    "rankingPontos": 1388.38,
    "rankingOrdem": 63,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/HAI"
  },
  {
    "cod": "SCO",
    "nome": "Escócia",
    "grupo": "C",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Steve Clarke",
    "rankingPosicao": 42,
    "rankingPontos": 1497.93,
    "rankingOrdem": 42,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/SCO"
  },
  {
    "cod": "USA",
    "nome": "Estados Unidos",
    "grupo": "D",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "CONCACAF",
    "tecnico": "Mauricio Pochettino",
    "rankingPosicao": 17,
    "rankingPontos": 1678.82,
    "rankingOrdem": 17,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/USA"
  },
  {
    "cod": "PAR",
    "nome": "Paraguai",
    "grupo": "D",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CONMEBOL",
    "tecnico": "Gustavo Alfaro",
    "rankingPosicao": 44,
    "rankingPontos": 1485.42,
    "rankingOrdem": 44,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAR"
  },
  {
    "cod": "AUS",
    "nome": "Austrália",
    "grupo": "D",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Tony Popovic",
    "rankingPosicao": 28,
    "rankingPontos": 1582.72,
    "rankingOrdem": 28,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUS"
  },
  {
    "cod": "TUR",
    "nome": "Turquia",
    "grupo": "D",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Vincenzo Montella",
    "rankingPosicao": 22,
    "rankingPontos": 1602.95,
    "rankingOrdem": 22,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUR"
  },
  {
    "cod": "GER",
    "nome": "Alemanha",
    "grupo": "E",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Julian Nagelsmann",
    "rankingPosicao": 10,
    "rankingPontos": 1735.77,
    "rankingOrdem": 10,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/GER"
  },
  {
    "cod": "CUW",
    "nome": "Curaçao",
    "grupo": "E",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CONCACAF",
    "tecnico": "Dick Advocaat",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CUW"
  },
  {
    "cod": "CIV",
    "nome": "Costa do Marfim",
    "grupo": "E",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Emerse Faé",
    "rankingPosicao": 35,
    "rankingPontos": 1532,
    "rankingOrdem": 35,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CIV"
  },
  {
    "cod": "ECU",
    "nome": "Equador",
    "grupo": "E",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "CONMEBOL",
    "tecnico": "Sebastián Beccacece",
    "rankingPosicao": 20,
    "rankingPontos": 1635.64,
    "rankingOrdem": 20,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/ECU"
  },
  {
    "cod": "NED",
    "nome": "Holanda",
    "grupo": "F",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Ronald Koeman",
    "rankingPosicao": 8,
    "rankingPontos": 1753.57,
    "rankingOrdem": 8,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/NED"
  },
  {
    "cod": "JPN",
    "nome": "Japão",
    "grupo": "F",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Hajime Moriyasu",
    "rankingPosicao": 18,
    "rankingPontos": 1661.38,
    "rankingOrdem": 18,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/JPN"
  },
  {
    "cod": "SWE",
    "nome": "Suécia",
    "grupo": "F",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Graham Potter",
    "rankingPosicao": 38,
    "rankingPontos": 1515.88,
    "rankingOrdem": 38,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/SWE"
  },
  {
    "cod": "TUN",
    "nome": "Tunísia",
    "grupo": "F",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Sabri Lamouchi",
    "rankingPosicao": 40,
    "rankingPontos": 1504.92,
    "rankingOrdem": 40,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUN"
  },
  {
    "cod": "BEL",
    "nome": "Bélgica",
    "grupo": "G",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Rudi Garcia",
    "rankingPosicao": 9,
    "rankingPontos": 1742.24,
    "rankingOrdem": 9,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/BEL"
  },
  {
    "cod": "EGY",
    "nome": "Egito",
    "grupo": "G",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Hossam Hassan",
    "rankingPosicao": 31,
    "rankingPontos": 1560.23,
    "rankingOrdem": 31,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/EGY"
  },
  {
    "cod": "IRN",
    "nome": "Irã",
    "grupo": "G",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Amir Ghalenoei",
    "rankingPosicao": 23,
    "rankingPontos": 1600.01,
    "rankingOrdem": 23,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRN"
  },
  {
    "cod": "NZL",
    "nome": "Nova Zelândia",
    "grupo": "G",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "OFC",
    "tecnico": "Darren Bazeley",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/NZL"
  },
  {
    "cod": "ESP",
    "nome": "Espanha",
    "grupo": "H",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Luis de la Fuente",
    "rankingPosicao": 2,
    "rankingPontos": 1874.71,
    "rankingOrdem": 2,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/ESP"
  },
  {
    "cod": "CPV",
    "nome": "Cabo Verde",
    "grupo": "H",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Pedro Leitão Brito",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CPV"
  },
  {
    "cod": "KSA",
    "nome": "Arábia Saudita",
    "grupo": "H",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Georgios Donis",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/KSA"
  },
  {
    "cod": "URU",
    "nome": "Uruguai",
    "grupo": "H",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "CONMEBOL",
    "tecnico": "Marcelo Bielsa",
    "rankingPosicao": 13,
    "rankingPontos": 1702.35,
    "rankingOrdem": 13,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/URU"
  },
  {
    "cod": "FRA",
    "nome": "França",
    "grupo": "I",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Didier Deschamps",
    "rankingPosicao": 3,
    "rankingPontos": 1870.7,
    "rankingOrdem": 3,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/FRA"
  },
  {
    "cod": "SEN",
    "nome": "Senegal",
    "grupo": "I",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Pape Thiaw",
    "rankingPosicao": 16,
    "rankingPontos": 1682.54,
    "rankingOrdem": 16,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/SEN"
  },
  {
    "cod": "IRQ",
    "nome": "Iraque",
    "grupo": "I",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Graham Arnold",
    "rankingPosicao": 67,
    "rankingPontos": 1368.99,
    "rankingOrdem": 67,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRQ"
  },
  {
    "cod": "NOR",
    "nome": "Noruega",
    "grupo": "I",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Ståle Solbakken",
    "rankingPosicao": 32,
    "rankingPontos": 1551.81,
    "rankingOrdem": 32,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/NOR"
  },
  {
    "cod": "ARG",
    "nome": "Argentina",
    "grupo": "J",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "CONMEBOL",
    "tecnico": "Lionel Scaloni",
    "rankingPosicao": 1,
    "rankingPontos": 1877.72,
    "rankingOrdem": 1,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/ARG"
  },
  {
    "cod": "ALG",
    "nome": "Argélia",
    "grupo": "J",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Vladimir Petković",
    "rankingPosicao": 29,
    "rankingPontos": 1571.65,
    "rankingOrdem": 29,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/ALG"
  },
  {
    "cod": "AUT",
    "nome": "Áustria",
    "grupo": "J",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Ralf Rangnick",
    "rankingPosicao": 27,
    "rankingPontos": 1587.22,
    "rankingOrdem": 27,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUT"
  },
  {
    "cod": "JOR",
    "nome": "Jordânia",
    "grupo": "J",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Jamal Sellami",
    "rankingPosicao": 61,
    "rankingPontos": 1397.9,
    "rankingOrdem": 61,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/JOR"
  },
  {
    "cod": "POR",
    "nome": "Portugal",
    "grupo": "K",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Roberto Martínez",
    "rankingPosicao": 5,
    "rankingPontos": 1767.85,
    "rankingOrdem": 5,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/POR"
  },
  {
    "cod": "COD",
    "nome": "RD Congo",
    "grupo": "K",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Sébastien Desabre",
    "rankingPosicao": 50,
    "rankingPontos": 1473,
    "rankingOrdem": 50,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/COD"
  },
  {
    "cod": "UZB",
    "nome": "Uzbequistão",
    "grupo": "K",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "AFC",
    "tecnico": "Fabio Cannavaro",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/UZB"
  },
  {
    "cod": "COL",
    "nome": "Colômbia",
    "grupo": "K",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "CONMEBOL",
    "tecnico": "Néstor Lorenzo",
    "rankingPosicao": 14,
    "rankingPontos": 1697.92,
    "rankingOrdem": 14,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/COL"
  },
  {
    "cod": "ENG",
    "nome": "Inglaterra",
    "grupo": "L",
    "pote": 1,
    "cabecaDeChave": true,
    "confederacao": "UEFA",
    "tecnico": "Thomas Tuchel",
    "rankingPosicao": 4,
    "rankingPontos": 1828.02,
    "rankingOrdem": 4,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/ENG"
  },
  {
    "cod": "CRO",
    "nome": "Croácia",
    "grupo": "L",
    "pote": 2,
    "cabecaDeChave": false,
    "confederacao": "UEFA",
    "tecnico": "Zlatko Dalic",
    "rankingPosicao": 11,
    "rankingPontos": 1720.07,
    "rankingOrdem": 11,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/CRO"
  },
  {
    "cod": "GHA",
    "nome": "Gana",
    "grupo": "L",
    "pote": 3,
    "cabecaDeChave": false,
    "confederacao": "CAF",
    "tecnico": "Carlos Queiroz",
    "rankingPosicao": null,
    "rankingPontos": null,
    "rankingOrdem": 99,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/GHA"
  },
  {
    "cod": "PAN",
    "nome": "Panamá",
    "grupo": "L",
    "pote": 4,
    "cabecaDeChave": false,
    "confederacao": "CONCACAF",
    "tecnico": "Thomas Christiansen",
    "rankingPosicao": 33,
    "rankingPontos": 1550.44,
    "rankingOrdem": 33,
    "bandeira": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAN"
  }
];
